import { Request, Response } from 'express';
import { runAnalise } from '../utils/analiseHumor';
import {
    getPsicologoByUserId,
    getPacienteByUserId,
    isPsicologoAssignedToPaciente,
    isValidObjectId,
} from '../utils/helpers';

const express = require('express');
const router  = express.Router();
const Alerta  = require('../models/alerta');
const { verifyToken }       = require('../middleware/VerifyToken');
const { verifyTokenByRole } = require('../middleware/VerifyTokenByRole');

// ─── POST /api/analise/paciente/:pacienteId/run ────────────────────────────────
// Runs the rule-based analysis on the last 7 Questionarios of a paciente.
// Psicologo: only for their own assigned pacientes.
// Paciente: only for their own profile.
router.post('/paciente/:pacienteId/run', verifyToken, verifyTokenByRole('psicologo', 'paciente'), async (req: Request, res: Response) => {
    try {
        const { pacienteId } = req.params;
        if (!isValidObjectId(pacienteId)) {
            return res.status(400).json({ error: 'ID de paciente inválido' });
        }

        if (req.user!.tipo === 'psicologo') {
            const assigned = await isPsicologoAssignedToPaciente(req.user!.id, pacienteId);
            if (!assigned) {
                return res.status(403).json({ error: 'Acesso negado: paciente não associado a este psicólogo' });
            }
            const psicologoProfile = await getPsicologoByUserId(req.user!.id);
            const result = await runAnalise(pacienteId, psicologoProfile._id.toString());
            return res.json(result);
        }

        if (req.user!.tipo === 'paciente') {
            const pacienteProfile = await getPacienteByUserId(req.user!.id);
            if (!pacienteProfile || pacienteProfile._id.toString() !== pacienteId) {
                return res.status(403).json({ error: 'Acesso negado: não pode correr análise de outro paciente' });
            }
            const result = await runAnalise(pacienteId, pacienteProfile.psicologo.toString());
            return res.json(result);
        }
    } catch (error) {
        res.status(500).json({ error: (error as Error).message });
    }
});

// ─── GET /api/analise/paciente/:pacienteId ─────────────────────────────────────
// Returns recent (last 7 days) alertas generated by the analysis engine for a paciente.
// Psicologo: only for their own assigned pacientes.
// Paciente: only for their own profile.
router.get('/paciente/:pacienteId', verifyToken, verifyTokenByRole('psicologo', 'paciente'), async (req: Request, res: Response) => {
    try {
        const { pacienteId } = req.params;
        if (!isValidObjectId(pacienteId)) {
            return res.status(400).json({ error: 'ID de paciente inválido' });
        }

        if (req.user!.tipo === 'psicologo') {
            const assigned = await isPsicologoAssignedToPaciente(req.user!.id, pacienteId);
            if (!assigned) {
                return res.status(403).json({ error: 'Acesso negado: paciente não associado a este psicólogo' });
            }
        }

        if (req.user!.tipo === 'paciente') {
            const pacienteProfile = await getPacienteByUserId(req.user!.id);
            if (!pacienteProfile || pacienteProfile._id.toString() !== pacienteId) {
                return res.status(403).json({ error: 'Acesso negado: não pode ver análise de outro paciente' });
            }
        }

        const cutoff = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
        const alertas = await Alerta.find({
            paciente: pacienteId,
            origem:   'analise',
            createdAt: { $gte: cutoff },
        }).sort({ createdAt: -1 });

        res.json(alertas);
    } catch (error) {
        res.status(500).json({ error: (error as Error).message });
    }
});

module.exports = { analiseRoutes: router };
