import { Request, Response } from 'express';
import { runAnalise } from '../utils/analiseHumor';
import {
    getPsicologoByUserId,
    isPsicologoAssignedToPaciente,
    isValidObjectId,
} from '../utils/helpers';

const express = require('express');
const router  = express.Router();
const Alerta  = require('../models/alerta');
const { verifyToken }       = require('../middleware/VerifyToken');
const { verifyTokenByRole } = require('../middleware/VerifyTokenByRole');

// ─── POST /api/analise/paciente/:pacienteId/run ────────────────────────────────
// Psicologo only. Runs the rule-based analysis on the last 7 Questionarios.
// Paciente does NOT run analysis — this is a clinical tool for the psicologo.
router.post('/paciente/:pacienteId/run', verifyToken, verifyTokenByRole('psicologo'), async (req: Request, res: Response) => {
    try {
        const { pacienteId } = req.params;
        if (!isValidObjectId(pacienteId)) {
            return res.status(400).json({ error: 'ID de paciente inválido' });
        }

        const assigned = await isPsicologoAssignedToPaciente(req.user!.id, pacienteId);
        if (!assigned) {
            return res.status(403).json({ error: 'Acesso negado: paciente não associado a este psicólogo' });
        }

        const psicologoProfile = await getPsicologoByUserId(req.user!.id);
        const result = await runAnalise(pacienteId, psicologoProfile._id.toString());
        return res.json(result);
    } catch (error) {
        res.status(500).json({ error: (error as Error).message });
    }
});

// ─── GET /api/analise/paciente/:pacienteId ─────────────────────────────────────
// Psicologo only. Returns recent alertas generated by the analysis engine.
// Paciente does NOT access analysis results — these are clinical risk alerts.
router.get('/paciente/:pacienteId', verifyToken, verifyTokenByRole('psicologo'), async (req: Request, res: Response) => {
    try {
        const { pacienteId } = req.params;
        if (!isValidObjectId(pacienteId)) {
            return res.status(400).json({ error: 'ID de paciente inválido' });
        }

        const assigned = await isPsicologoAssignedToPaciente(req.user!.id, pacienteId);
        if (!assigned) {
            return res.status(403).json({ error: 'Acesso negado: paciente não associado a este psicólogo' });
        }

        const cutoff = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
        const alertas = await Alerta.find({
            paciente: pacienteId,
            origem:   'analise',
            createdAt: { $gte: cutoff },
        }).sort({ createdAt: -1 });

        res.json(alertas);
    } catch (error) {
        res.status(500).json({ error: (error as Error).message });
    }
});

module.exports = { analiseRoutes: router };
